# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'dsyfer'

target 'dsyfer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'  
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'master'



  # Pods for dsyfer

end
